FRED_SERIES = [
    {
        "source_series_id": "DGS3MO",
        "name": "3-Month Treasury Constant Maturity Rate",
        "description": "Market yield on U.S. Treasury securities at 3-month constant maturity.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "daily",
        "maturity": "3M",
    },
    {
        "source_series_id": "DGS2",
        "name": "2-Year Treasury Constant Maturity Rate",
        "description": "Market yield on U.S. Treasury securities at 2-year constant maturity.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "daily",
        "maturity": "2Y",
    },
    {
        "source_series_id": "DGS5",
        "name": "5-Year Treasury Constant Maturity Rate",
        "description": "Market yield on U.S. Treasury securities at 5-year constant maturity.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "daily",
        "maturity": "5Y",
    },
    {
        "source_series_id": "DGS10",
        "name": "10-Year Treasury Constant Maturity Rate",
        "description": "Market yield on U.S. Treasury securities at 10-year constant maturity.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "daily",
        "maturity": "10Y",
    },
    {
        "source_series_id": "DGS30",
        "name": "30-Year Treasury Constant Maturity Rate",
        "description": "Market yield on U.S. Treasury securities at 30-year constant maturity.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "daily",
        "maturity": "30Y",
    },
    {
        "source_series_id": "FEDFUNDS",
        "name": "Federal Funds Effective Rate",
        "description": "Effective federal funds rate.",
        "category": "rates",
        "geography": "US",
        "unit": "percent",
        "frequency": "monthly",
        "maturity": None,
    },
    {
        "source_series_id": "T10Y2Y",
        "name": "10-Year Treasury Minus 2-Year Treasury Spread",
        "description": "Spread between the 10-year and 2-year Treasury constant maturity rates.",
        "category": "rates",
        "geography": "US",
        "unit": "percentage points",
        "frequency": "daily",
        "maturity": None,
    },
]
